Repository hashicorp/terraform-website, pull requests merged in 2020-06, with the labels that each got.

#1288 Add v2 Upgrade Guide for SDK.
  content/source/docs/extend/guides/v2-upgrade-guide.html.md
  content/source/layouts/extend.erb
Labels: extending

#1296 Added Azure DevOps formatting
  content/source/docs/cloud/integrations/service-now/index.html.md
Labels: clarification

#1321 Updating latest supported version for CentOS and RHEL
  content/source/docs/enterprise/before-installing/centos-requirements.html.md
  content/source/docs/enterprise/before-installing/index.html.md
  content/source/docs/enterprise/before-installing/rhel-requirements.html.md
Labels: inaccuracy
