Repository hashicorp/terraform-website, pull requests merged in 2020-09, with the labels that each got.

#1432 Update docs to incl. newly implemented module functions
  content/source/docs/cloud/sentinel/import/tfconfig-v2.html.md
Labels: extending

#1437 Remove errant single quotes
  content/source/docs/enterprise/admin/automated-recovery.html.md
Labels: inaccuracy

#1446 Move the upgrade guide under our guides section.
  content/redirects.txt
  content/source/docs/extend/guides/v1-upgrade-guide.html.md
  content/source/layouts/extend.erb
Labels: enhancement

#1461 Add new tfce aws resources
  content/source/docs/cloud/cost-estimation/aws.html.md
Labels: inaccuracy, tfc
