Repository hashicorp/terraform-website, pull requests merged in 2020-10, with the labels that each got.

#1459 Update all Learn crosslinks within terraform-website
  content/source/docs/cloud/cost-estimation/index.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.1.html.md
  content/source/docs/cloud/index.html.md
  content/source/docs/cloud/migrate/index.html.md
  content/source/docs/cloud/overview.html.md
  content/source/docs/cloud/registry/index.html.md
  content/source/docs/cloud/registry/publish.html.md
  content/source/docs/cloud/registry/using.html.md
  content/source/docs/cloud/run/cli.html.md
  content/source/docs/cloud/run/index.html.md
  content/source/docs/cloud/sentinel/enforce.html.md
  content/source/docs/cloud/sentinel/examples.html.md
  content/source/docs/cloud/sentinel/index.html.md
  content/source/docs/cloud/sentinel/manage-policies.html.md
  content/source/docs/cloud/users-teams-organizations/permissions.html.md
  content/source/docs/cloud/users-teams-organizations/teams.html.md
  content/source/docs/cloud/workspaces/creating.html.md
  content/source/docs/cloud/workspaces/index.html.md
  content/source/docs/cloud/workspaces/run-triggers.html.md
  content/source/docs/enterprise/install/config.html.md
  content/source/docs/extend/community/contributing.html.md
  content/source/docs/extend/index.html.md
  content/source/docs/extend/resources/index.html.md
  content/source/docs/glossary.html.md
  content/source/docs/index.html.markdown
  content/source/downloads.html.erb
  content/source/layouts/_cloud_content.erb
  content/source/layouts/_otherdocs.erb
  content/source/layouts/extend.erb
Labels: clarification

#1466 extend: Correct link for switching to the standalone SDK
  content/source/docs/extend/terraform-0.12-compatibility.html.md
Labels: inaccuracy

#1472 add instructions for using custom providers in TFC/E with TF 0.13
  content/source/docs/cloud/run/install-software.html.md
Labels: clarification, inaccuracy

#1481 Icons: Replace "outbound link" icon for aesthetic reasons
  content/source/assets/images/outbound-link.svg
  content/source/layouts/_cloud_content.erb
  content/source/layouts/extend.erb
  content/source/layouts/inner.erb
Labels: cosmetic bug

#1484 Add new TFCE Azure resources
  content/source/docs/cloud/cost-estimation/azure.html.md
Labels: inaccuracy

#1482 Site behavior: Add GA tracking segment for 404 referrers
  content/source/404.html.md
  content/source/layouts/404.erb
Labels: enhancement

#1483 Styles: Make code spans usable in sidebar navs
  content/source/assets/stylesheets/_docs.scss
Labels: cosmetic bug

#1480 Remove extra text and heading from Enterprise index
  content/source/docs/enterprise/index.html.md
Labels: clarification

#1486 Adding documentation explaining blob storage authentication
  content/source/docs/cloud/api/index.html.md
Labels: clarification, tfc
