Repository hashicorp/terraform-website, pull requests merged in 2020-01, with the labels that each got.

#1070 update cost estimation settings screenshot
  content/source/docs/enterprise/admin/images/admin-cost-estimation.png
Labels: ptfe

#1076 Amend variables map to reflect recent changes and incl category attribute
  content/source/docs/cloud/sentinel/import/tfrun.html.md
Labels: enhancement

#1080 20564/update okta saml sign on docs
  .github/pull_request_template.md
  README.md
  content/source/docs/enterprise/saml/identity-provider-configuration-okta.html.md
  content/source/docs/enterprise/saml/images/login/sso_sign_in.png
  content/source/docs/enterprise/saml/login.html.md
Labels: enhancement, ptfe

#1051 Changes for SN v1.1.0
  content/source/docs/cloud/integrations/service-now/example-customizations.html.md
  content/source/docs/cloud/integrations/service-now/images/service-now-create-catalog-item.png
  content/source/docs/cloud/integrations/service-now/images/service-now-create-var-set.png
  content/source/docs/cloud/integrations/service-now/index.html.md
  content/source/layouts/cloud.erb
Labels: ptfe

#1088 Updated TFCE support list
  content/source/docs/cloud/cost-estimation/azure.html.md
Labels: enhancement
