Repository hashicorp/terraform-website, pull requests merged in 2020-11, with the labels that each got.

#1490 Adding new attributes for Sentinel tfrun import
  content/source/docs/cloud/sentinel/import/tfrun.html.md
Labels: inaccuracy, new docs

#1493 Task/add aws instance profile option info
  content/source/docs/enterprise/admin/images/README.md
  content/source/docs/enterprise/admin/images/admin-cost-estimation.png
  content/source/docs/enterprise/admin/integration.html.md
Labels: new docs

#1498 TF Core: add symlink to `language.erb` layout
  content/source/layouts/language.erb
Labels: enhancement

#1502 outputs only from root module
  content/source/docs/cloud/sentinel/import/tfstate-v2.html.md
Labels: inaccuracy

#1501 Add deprecation notice for Bitbucket Server v5.3.0 and below
  content/source/docs/cloud/vcs/bitbucket-server.html.md
  content/source/docs/cloud/vcs/images/bitbucket-server-tfe-add-url-fields.png
Labels: clarification

#1505 Multipool agents
  content/redirects.txt
  content/source/docs/cloud/agents/images/agent-delete-invalid.png
  content/source/docs/cloud/agents/images/agent-delete-valid-confirm.png
  content/source/docs/cloud/agents/images/agent-delete-valid.png
  content/source/docs/cloud/agents/images/agent-execution-mode.png
  content/source/docs/cloud/agents/images/agent-first-pool-name.png
  content/source/docs/cloud/agents/images/agent-first-pool-tokens.png
  content/source/docs/cloud/agents/images/agent-first-pool.png
  content/source/docs/cloud/agents/images/agent-idle.png
  content/source/docs/cloud/agents/images/agent-revoke-token-confirm.png
  content/source/docs/cloud/agents/images/agent-revoke-token.png
  content/source/docs/cloud/agents/images/agent-run-details.png
  content/source/docs/cloud/agents/images/agent-statuses.png
  content/source/docs/cloud/agents/index.html.md
  content/source/docs/cloud/api/agents.md
  content/source/docs/cloud/api/applies.md
  content/source/docs/cloud/api/plans.html.md
  content/source/docs/cloud/users-teams-organizations/api-tokens.html.md
  content/source/docs/cloud/workspaces/images/agent-enter-token-description.png
  content/source/docs/cloud/workspaces/images/agent-first-time-agent-token.png
  content/source/docs/cloud/workspaces/images/agent-new-token.png
  content/source/docs/cloud/workspaces/images/agent-running.png
  content/source/docs/cloud/workspaces/images/agent-statuses.png
  content/source/docs/cloud/workspaces/images/agent-token-description.png
  content/source/docs/cloud/workspaces/images/agent-tokens-list.png
  content/source/docs/cloud/workspaces/images/agent-workspace-execution-mode.png
  content/source/docs/cloud/workspaces/settings.html.md
  content/source/layouts/_cloud_content.erb
Labels: enhancement, tfc

#1517 Adopt registry docs into terraform-website repo
  content/source/docs/index.html.markdown
  content/source/docs/registry
  content/source/docs/registry/api.html.md
  content/source/docs/registry/images/registry-issue.png
  content/source/docs/registry/images/registry1.png
  content/source/docs/registry/images/registry2.png
  content/source/docs/registry/images/user-account.png
  content/source/docs/registry/index.html.md
  content/source/docs/registry/modules/images/registry-verified.png
  content/source/docs/registry/modules/publish.html.md
  content/source/docs/registry/modules/use.html.md
  content/source/docs/registry/modules/verified.html.md
  content/source/docs/registry/private.html.md
  content/source/docs/registry/providers/docs.html.md
  content/source/docs/registry/providers/images/archived-tier.png
  content/source/docs/registry/providers/images/community-tier.png
  content/source/docs/registry/providers/images/github-oauth-permissions.png
  content/source/docs/registry/providers/images/official-tier.png
  content/source/docs/registry/providers/images/publishing.png
  content/source/docs/registry/providers/images/verified-tier.png
  content/source/docs/registry/providers/index.html.md
  content/source/docs/registry/providers/os-arch.html.md
  content/source/docs/registry/providers/publishing.html.md
  content/source/layouts/_otherdocs.erb
  content/source/layouts/layout.erb
  content/source/layouts/registry.erb
Labels: enhancement
