Repository hashicorp/terraform-website, pull requests merged in 2020-05, with the labels that each got.

#1231 VCS Connection Creation doc update
  content/source/docs/cloud/vcs/azure-devops-server.html.md
  content/source/docs/cloud/vcs/azure-devops-services.html.md
  content/source/docs/cloud/vcs/bitbucket-cloud.html.md
  content/source/docs/cloud/vcs/bitbucket-server.html.md
  content/source/docs/cloud/vcs/github-enterprise.html.md
  content/source/docs/cloud/vcs/github.html.md
  content/source/docs/cloud/vcs/gitlab-com.html.md
  content/source/docs/cloud/vcs/gitlab-eece.html.md
  content/source/docs/cloud/vcs/images/azure-devops-server-add-private-key.png
  content/source/docs/cloud/vcs/images/azure-devops-server-add-vcs-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-server-configure-settings.png
  content/source/docs/cloud/vcs/images/azure-devops-server-create-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-server-setup-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-services-add-vcs-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-services-connect-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-services-create-provider.png
  content/source/docs/cloud/vcs/images/azure-devops-services-ssh-key.png
  content/source/docs/cloud/vcs/images/azure-devops-services-tfe-secret.png
  content/source/docs/cloud/vcs/images/bitbucket-cloud-add-consumer.png
  content/source/docs/cloud/vcs/images/bitbucket-cloud-edit-consumer.png
  content/source/docs/cloud/vcs/images/bitbucket-cloud-ssh-key.png
  content/source/docs/cloud/vcs/images/bitbucket-cloud-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/bitbucket-cloud-tfe-callback-url.png
  content/source/docs/cloud/vcs/images/bitbucket-server-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/bitbucket-server-tfe-add-private-key.png
  content/source/docs/cloud/vcs/images/bitbucket-server-tfe-add-url-fields.png
  content/source/docs/cloud/vcs/images/bitbucket-server-tfe-consumer-and-public-key.png
  content/source/docs/cloud/vcs/images/gh-ssh-key.png
  content/source/docs/cloud/vcs/images/gh-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/gh-tfe-callback-url.png
  content/source/docs/cloud/vcs/images/ghe-ssh-key.png
  content/source/docs/cloud/vcs/images/ghe-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/ghe-tfe-add-url-fields.png
  content/source/docs/cloud/vcs/images/gitlab-application-created.png
  content/source/docs/cloud/vcs/images/gitlab-application-settings.png
  content/source/docs/cloud/vcs/images/gitlab-authorize.png
  content/source/docs/cloud/vcs/images/gitlab-com-ssh-key.png
  content/source/docs/cloud/vcs/images/gitlab-com-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/gitlab-eece-ssh-key.png
  content/source/docs/cloud/vcs/images/gitlab-eece-tfe-add-client-fields.png
  content/source/docs/cloud/vcs/images/gitlab-eece-tfe-add-url-fields.png
  content/source/docs/cloud/vcs/images/gitlab-tfe-callback-url.png
Labels: tfc

#1227 Updated the Managing Sentinel Policies documentation to incl. Sentinel Modules
  content/source/docs/cloud/sentinel/manage-policies.html.md
Labels: extending

#1258 specify that cost estimation makes calls in "us-east-1".
  content/source/docs/enterprise/admin/integration.html.md
Labels: clarification, tfc

#1259 update supported TFCE resources
  content/source/docs/cloud/cost-estimation/aws.html.md
  content/source/docs/cloud/cost-estimation/azure.html.md
  content/source/docs/cloud/cost-estimation/gcp.html.md
Labels: clarification, tfc

#1216 Documentation for new TFE "allow speculative plans on pull requests from forks" setting
  content/source/docs/cloud/api/admin/settings.html.md
  content/source/docs/cloud/api/organization-memberships.html.md
  content/source/docs/cloud/run/ui.html.md
  content/source/docs/cloud/vcs/index.html.md
  content/source/docs/enterprise/admin/general.html.md
  content/source/docs/glossary.html.md
Labels: new docs, ptfe, tfc
