Repository hashicorp/terraform-website, pull requests merged in 2020-12, with the labels that each got.

#1520 0.14 release task: ship language and cli docs
  content/source/docs/cloud/guides/recommended-practices/index.html.md
  content/source/docs/cloud/guides/recommended-practices/part1.html.md
  content/source/docs/cloud/guides/recommended-practices/part2.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.1.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.2.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.3.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.4.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.html.md
  content/source/docs/index.html.markdown
  content/source/layouts/_otherdocs.erb
  content/source/layouts/layout.erb
Labels: enhancement, new docs

#1533 Replace es6-isms in hashi-stack-menu
  content/source/assets/javascripts/hashi-stack-menu/main.js
Labels: enhancement, inaccuracy

#1535 Update audit trail docs to match API doc styling
  content/source/docs/cloud/api/audit-trails.html.md
Labels: cosmetic bug

#1528 Add correct references for connecting Splunk to TFC.
  content/source/docs/cloud/integrations/splunk/index.html.md
Labels: clarification

#1508 Mention overriding soft-mandatory policies in CLI
  content/source/docs/cloud/run/cli.html.md
Labels: clarification

#1538 Fix typo in gitlab-eece documentation
  content/source/docs/cloud/vcs/gitlab-eece.html.md
Labels: cosmetic bug

#1541 Fix persistent nasty bug with navigating to anchor links
  content/source/assets/javascripts/application.js
Labels: cosmetic bug, enhancement

#1540 Update Azure AD to Microsoft Azure AD
  content/source/docs/cloud/users-teams-organizations/single-sign-on.html.md
  content/source/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html.md
Labels: clarification

#1548 Re-order items in "other docs" section of nav sidebar
  content/source/layouts/_otherdocs.erb
Labels: clarification

#1546 Fix some broken links
  content/scripts/testdata/incoming-links.txt
  content/source/docs/cloud/run/cli.html.md
Labels: inaccuracy

#1545 readme: Add Learn crosslink snippet markup, next to callouts
  README.md
Labels: clarification

#1551 CI: Separate the upload and cache warming steps to distinguish broken links from broken builds
  .circleci/config.yml
  content/scripts/deploy.sh
  content/scripts/upload.sh
  content/scripts/warm-cache.sh
Labels: enhancement

#1521 Post-0.14 release task: Remove symlinks to deleted sidebar navs
  content/source/layouts/backend-types.erb
  content/source/layouts/commands-providers.erb
  content/source/layouts/commands-state.erb
  content/source/layouts/commands-workspace.erb
  content/source/layouts/functions.erb
  content/source/layouts/guides.erb
Labels: enhancement

#1557 Remove unused property from workspace requests and responses
  content/source/docs/cloud/api/workspaces.html.md
Labels: inaccuracy

#1561 Circle configs: replace wget with linkcheck
  .circleci/config.yml
  content/source/layouts/_sidebar.erb
  content/source/layouts/layout.erb
Labels: enhancement, inaccuracy

#1564 Broken/wobbly link fixes
  content/source/docs/cloud/api/agents.md
  content/source/docs/cloud/api/audit-trails.html.md
  content/source/docs/cloud/api/index.html.md
  content/source/docs/cloud/api/policies.html.md
  content/source/docs/cloud/api/state-versions.html.md
  content/source/docs/cloud/api/team-access.html.md
  content/source/docs/cloud/guides/recommended-practices/part3.2.html.md
  content/source/docs/cloud/migrate/index.html.md
  content/source/docs/cloud/migrate/workspaces.html.md
  content/source/docs/cloud/overview.html.md
  content/source/docs/cloud/registry/publish.html.md
  content/source/docs/cloud/run/cli.html.md
  content/source/docs/cloud/sentinel/enforce.html.md
  content/source/docs/cloud/sentinel/import/index.html.md
  content/source/docs/cloud/sentinel/import/tfconfig.html.md
  content/source/docs/cloud/sentinel/import/tfplan-v2.html.md
  content/source/docs/cloud/sentinel/import/tfplan.html.md
  content/source/docs/cloud/sentinel/import/tfrun.html.md
  content/source/docs/cloud/sentinel/import/tfstate.html.md
  content/source/docs/cloud/sentinel/index.html.md
  content/source/docs/cloud/sentinel/manage-policies.html.md
  content/source/docs/cloud/sentinel/sentinel-tf-012.html.md
  content/source/docs/cloud/users-teams-organizations/organizations.html.md
  content/source/docs/cloud/users-teams-organizations/permissions.html.md
  content/source/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html.md
  content/source/docs/cloud/users-teams-organizations/single-sign-on/okta.html.md
  content/source/docs/cloud/users-teams-organizations/single-sign-on/saml.html.md
  content/source/docs/cloud/users-teams-organizations/teams.html.md
  content/source/docs/cloud/workspaces/access.html.md
  content/source/docs/cloud/workspaces/creating.html.md
  content/source/docs/cloud/workspaces/ssh-keys.html.md
  content/source/docs/cloud/workspaces/variables.html.md
  content/source/docs/cloud/workspaces/vcs.html.md
  content/source/docs/enterprise/admin/upgrades.html.md
  content/source/docs/enterprise/before-installing/index.html.md
  content/source/docs/enterprise/install/cluster-azure.html.md
  content/source/docs/enterprise/install/installer.html.md
  content/source/docs/extend/community/index.html.md
  content/source/docs/extend/community/maintainers.html.md
  content/source/docs/extend/index.html.md
  content/source/docs/glossary.html.md
  content/source/docs/registry/modules/publish.html.md
  content/source/docs/registry/providers/publishing.html.md
Labels: inaccuracy

#1566 Fix redirecting tfe provider links in glossary
  content/source/docs/glossary.html.md
Labels: cosmetic bug

#1570 Redirect provider category indexes to main provider docs page
  content/redirects.txt
  content/scripts/testdata/incoming-links.txt
Labels: inaccuracy

#1572 Update the glossary's table of contents
  content/source/docs/glossary.html.md
Labels: inaccuracy
