Repository hashicorp/terraform-website, pull requests merged in 2021-04, with the labels that each got.

#1673 Remove badges from the HashiStackMenu
  content/source/layouts/layout.erb
Labels: web platform

#1676 Update users.html.md - remove suggestion to use private API
  content/source/docs/cloud/api/admin/users.html.md
Labels: clarification

#1679 Update agent documentation to clarify shutdown
  content/source/docs/cloud/agents/index.html.md
Labels: clarification, inaccuracy

#1628 Fix alphabetization of TFC API TOC
  content/source/layouts/_cloud_content.erb
Labels: cosmetic bug

#1682 Add section for includes to Run Triggers API
  content/source/docs/cloud/api/run-triggers.html.md
Labels: new docs

#1694 Amend VMware RA diagram to promote happy path
  content/source/docs/enterprise/before-installing/reference-architecture/assets/vmware-mounted-disk-infrastructure-diagram.png
Labels: enhancement
