Repository hashicorp/terraform-website, pull requests merged in 2021-11, with the labels that each got.

#1936 clarify agents/tfe compatibility
  content/source/docs/enterprise/admin/agents-on-tfe.html.md
Labels: clarification

#1938 Document `tfe-admin list-nodes` command
  content/source/docs/enterprise/admin/active-active.html.md
Labels: new docs

#1934 update hashicorp/middleman-hashicorp Docker image
  .circleci/config.yml
Labels: dependencies

#1949 update next scheduled TFE release
  content/source/docs/enterprise/release/index.html.md
Labels: clarification

#1947 Sentinel mocks are available indefinitely
  content/source/docs/cloud/sentinel/mock.html.md
Labels: tfc, tw-reviewed

#1930 Draft Variable Sets API docs
  content/source/docs/cloud/api/changelog.html.md
  content/source/docs/cloud/api/variable-sets.html.md
Labels: tw-reviewed

#1950 [DO NOT MERGE] Add new documentation for variable sets
  content/source/docs/cloud/api/changelog.html.md
  content/source/docs/cloud/api/variable-sets.html.md
  content/source/docs/cloud/users-teams-organizations/images/org-settings.png
  content/source/docs/cloud/users-teams-organizations/organizations.html.md
  content/source/docs/cloud/workspaces/images/create-var-set.png
  content/source/docs/cloud/workspaces/images/ui-overwritten-variables.png
  content/source/docs/cloud/workspaces/images/var-sets-page.png
  content/source/docs/cloud/workspaces/images/variable-precedence-example.png
  content/source/docs/cloud/workspaces/images/vars-edit.png
  content/source/docs/cloud/workspaces/images/vars.png
  content/source/docs/cloud/workspaces/managing-variables.html.md
  content/source/docs/cloud/workspaces/variables.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs, tfc

#1945 Update docs sidebar and dropdown
  content/source/layouts/_otherdocs.erb
  content/source/layouts/extend.erb
  content/source/layouts/layout.erb
Labels: enhancement

#1919 Add send-passing-statuses-for-untriggered-speculative-plans
  content/source/docs/cloud/api/admin/settings.html.md
  content/source/docs/cloud/api/organizations.html.md
Labels: new docs, tfc, tw-reviewed, api

#1918 Update TFC related content
  content/source/docs/enterprise/index.html.md
Labels: tw-reviewed

#1926 Zisom change permission statements
  content/source/docs/cloud/api/configuration-versions.html.md
  content/source/docs/cloud/run/api.html.md
Labels: inaccuracy, tw-reviewed

#1927 Tf api/pagination 1
  content/source/docs/cloud/api/changelog.html.md
  content/source/docs/cloud/api/feature-sets.html.md
  content/source/docs/cloud/api/notification-configurations.html.md
  content/source/docs/cloud/api/oauth-clients.html.md
  content/source/docs/cloud/api/oauth-tokens.html.md
  content/source/docs/cloud/api/organizations.html.md
  content/source/docs/cloud/api/policy-checks.html.md
  content/source/docs/cloud/api/policy-set-params.html.md
  content/source/docs/cloud/api/ssh-keys.html.md
  content/source/docs/cloud/api/user-tokens.md
Labels: new docs, tfc, tw-reviewed, api

#1968 Replace HTML tables with Markdown tables
  content/source/docs/enterprise/install/active-active.html.md
Labels: cosmetic bug

#1972 GET /teams - all GET endpoints
  content/source/docs/cloud/api/teams.html.md
Labels: inaccuracy, clarification, tfc, api

#1951 Public provider curation api docs
  content/source/docs/cloud/api/changelog.html.md
  content/source/docs/cloud/api/index.html.md
  content/source/docs/cloud/api/providers.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs, tfc, tw-reviewed

#1928 Update RHEL worker section with UBI and envdir
  content/source/docs/enterprise/install/installer.html.md
Labels: tw-reviewed

#1976 Update run task screenshots and docs
  content/source/docs/cloud/workspaces/images/run-tasks-add-to-organization.png
  content/source/docs/cloud/workspaces/images/run-tasks-add-to-workspace.png
  content/source/docs/cloud/workspaces/images/run-tasks-blank-event-hooks.png
  content/source/docs/cloud/workspaces/images/run-tasks-delete-hook-warning.png
  content/source/docs/cloud/workspaces/images/run-tasks-delete-run-task-warning.png
  content/source/docs/cloud/workspaces/images/run-tasks-empty-run-tasks.png
  content/source/docs/cloud/workspaces/images/run-tasks-event-hooks-populated.png
  content/source/docs/cloud/workspaces/images/run-tasks-final-workspace-configuration.png
  content/source/docs/cloud/workspaces/images/run-tasks-populated.png
  content/source/docs/cloud/workspaces/images/run-tasks-run-failed.png
  content/source/docs/cloud/workspaces/images/run-tasks-run-success.png
  content/source/docs/cloud/workspaces/images/run-tasks-run-tasks-populated.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-remove.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-run-tasks-populated.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-settings.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-tasks-populated.png
  content/source/docs/cloud/workspaces/run-tasks.html.md
Labels: cosmetic bug

#1941 [DO NOT MERGE] Update pages and images to support adding public providers to registry
  content/source/docs/cloud/overview.html.md
  content/source/docs/cloud/registry/add.html.md
  content/source/docs/cloud/registry/design.html.md
  content/source/docs/cloud/registry/images/add-find-button.png
  content/source/docs/cloud/registry/images/add-search-public-modules-providers.png
  content/source/docs/cloud/registry/images/add-search-public-modules.png
  content/source/docs/cloud/registry/images/registry-button.png
  content/source/docs/cloud/registry/images/registry-page-filtered.png
  content/source/docs/cloud/registry/images/using-modules-button.png
  content/source/docs/cloud/registry/images/using-modules-list-shared.png
  content/source/docs/cloud/registry/images/using-submodules-dropdown.png
  content/source/docs/cloud/registry/index.html.md
  content/source/docs/cloud/registry/publish.html.md
  content/source/docs/cloud/registry/using.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs, tfc

#1974 Replace ; with . for all Query Parameters blocks
  content/source/docs/cloud/api/agent-tokens.md
  content/source/docs/cloud/api/agents.md
  content/source/docs/cloud/api/audit-trails.html.md
  content/source/docs/cloud/api/feature-sets.html.md
  content/source/docs/cloud/api/modules.html.md
  content/source/docs/cloud/api/notification-configurations.html.md
  content/source/docs/cloud/api/organization-memberships.html.md
  content/source/docs/cloud/api/organizations.html.md
  content/source/docs/cloud/api/policy-checks.html.md
  content/source/docs/cloud/api/policy-set-params.html.md
  content/source/docs/cloud/api/run-tasks.html.md
  content/source/docs/cloud/api/ssh-keys.html.md
  content/source/docs/cloud/api/state-versions.html.md
  content/source/docs/cloud/api/teams.html.md
  content/source/docs/cloud/api/variables.html.md
  content/source/docs/cloud/api/vcs-events.html.md
  content/source/docs/cloud/api/workspaces.html.md
Labels: tfc, api

#1986 Replace ; with . for all Query Parameters blocks
  content/source/docs/cloud/api/admin/organizations.html.md
  content/source/docs/cloud/api/admin/runs.html.md
  content/source/docs/cloud/api/admin/terraform-versions.html.md
  content/source/docs/cloud/api/admin/users.html.md
  content/source/docs/cloud/api/admin/workspaces.html.md
  content/source/docs/cloud/api/configuration-versions.html.md
  content/source/docs/cloud/api/oauth-clients.html.md
  content/source/docs/cloud/api/oauth-tokens.html.md
  content/source/docs/cloud/api/providers.html.md
  content/source/docs/cloud/api/user-tokens.md
Labels: tfc, api

#1980 Clarify software requirements of Terraform Enterprise
  content/source/docs/enterprise/before-installing/index.html.md
Labels: tw-reviewed
