Repository hashicorp/terraform-website, pull requests merged in 2021-07, with the labels that each got.

#1754 Add note about cost estimation enabled by default
  content/source/docs/cloud/cost-estimation/index.html.md
Labels: clarification

#1756 Adding missing bullet point
  content/source/docs/enterprise/install/automating-the-installer.html.md
Labels: cosmetic bug

#1759 Add doc preview from terraform repo
  README.md
Labels: clarification

#1760 Fixing error in tfrun documentation
  content/source/docs/cloud/sentinel/import/tfrun.html.md
Labels: inaccuracy

#1762 Link refresh tutorial from cloud run modes and options page
  content/source/docs/cloud/run/modes-and-options.html.md
Labels: tfc

#1768 Redirect legacy provider docs index
  content/redirects.txt
Labels: inaccuracy

#1767 Update ReadMe with cherry-pick instrutions for terraform repo
  README.md
Labels: clarification

#1656 Update policy-set-params.html.md
  content/source/docs/cloud/api/policy-set-params.html.md
Labels: inaccuracy

#1670 remove single module comments
  content/source/docs/cloud/registry/publish.html.md
Labels: inaccuracy

#1712 Sentinel: Update information for mock generation
  content/source/docs/cloud/sentinel/mock.html.md
Labels: clarification, inaccuracy

#1769 Rename the Extend section, revamp the sidebar.
  README.md
  content/redirects.txt
  content/source/docs/extend/best-practices/depending-on-providers.html.md
  content/source/docs/extend/best-practices/deprecations.md
  content/source/docs/extend/best-practices/detecting-drift.html.md
  content/source/docs/extend/best-practices/index.html.md
  content/source/docs/extend/best-practices/naming.html.md
  content/source/docs/extend/best-practices/other-languages.html.md
  content/source/docs/extend/best-practices/sensitive-state.html.md
  content/source/docs/extend/best-practices/testing.html.md
  content/source/docs/extend/best-practices/versioning.html.md
  content/source/docs/extend/community/code-of-conduct.html.md
  content/source/docs/extend/community/contributing.html.md
  content/source/docs/extend/community/events/2018/fall-gardening.html.md
  content/source/docs/extend/community/events/2018/summer-gardening.html.md
  content/source/docs/extend/community/events/index.html.md
  content/source/docs/extend/community/index.html.md
  content/source/docs/extend/community/maintainers.html.md
  content/source/docs/extend/debugging.html.md
  content/source/docs/extend/hashicorp-provider-design-principles.html.md
  content/source/docs/extend/how-terraform-works.html.md
  content/source/docs/extend/index.html.md
  content/source/docs/extend/plugin-types.html.md
  content/source/docs/extend/schemas/index.html.md
  content/source/docs/extend/schemas/schema-behaviors.html.md
  content/source/docs/extend/schemas/schema-methods.html.md
  content/source/docs/extend/schemas/schema-types.html.md
  content/source/docs/extend/testing/acceptance-tests/index.html.md
  content/source/docs/extend/testing/acceptance-tests/sweepers.html.md
  content/source/docs/extend/testing/acceptance-tests/testcase.html.md
  content/source/docs/extend/testing/acceptance-tests/teststep.html.md
  content/source/docs/extend/testing/index.html.md
  content/source/docs/extend/testing/testing-api.html.md
  content/source/docs/extend/testing/testing-patterns.html.md
  content/source/docs/extend/testing/unit-testing.html.md
  content/source/docs/extend/writing-custom-providers.html.md
  content/source/docs/glossary.html.md
  content/source/docs/index.html.markdown
  content/source/docs/registry/index.html.md
  content/source/layouts/_otherdocs.erb
  content/source/layouts/extend.erb
  content/source/layouts/layout.erb
  content/source/layouts/registry.erb
  content/source/layouts/terraform-glossary.erb
Labels: clarification, extending

#1706 Update admin API paths
  content/source/docs/cloud/api/admin/organizations.html.md
  content/source/docs/cloud/api/admin/runs.html.md
  content/source/docs/cloud/api/admin/terraform-versions.html.md
  content/source/docs/cloud/api/admin/users.html.md
  content/source/docs/cloud/api/admin/workspaces.html.md
Labels: tw-reviewed

#1743 Add search query to workspace list
  content/source/docs/cloud/api/workspaces.html.md
Labels: tw-reviewed

#1778 Update API changelog with a new org token permission
  content/source/docs/cloud/api/changelog.html.md
Labels: inaccuracy, tw-reviewed

#1775 Add framework docs
  content/redirects.txt
  content/source/docs/extend/best-practices/detecting-drift.html.md
  content/source/docs/extend/best-practices/index.html.md
  content/source/docs/extend/best-practices/naming.html.md
  content/source/docs/extend/best-practices/testing.html.md
  content/source/docs/extend/debugging.html.md
  content/source/docs/extend/index.html.md
  content/source/docs/extend/schemas/index.html.md
  content/source/docs/extend/schemas/schema-behaviors.html.md
  content/source/docs/extend/schemas/schema-types.html.md
  content/source/docs/extend/testing/acceptance-tests/index.html.md
  content/source/docs/extend/testing/acceptance-tests/sweepers.html.md
  content/source/docs/extend/testing/acceptance-tests/testcase.html.md
  content/source/docs/extend/testing/acceptance-tests/teststep.html.md
  content/source/docs/extend/testing/index.html.md
  content/source/docs/extend/testing/unit-testing.html.md
  content/source/docs/plugin/framework/accessing-values.html.md
  content/source/docs/plugin/framework/acctests.html.md
  content/source/docs/plugin/framework/data-sources.html.md
  content/source/docs/plugin/framework/diagnostics.html.md
  content/source/docs/plugin/framework/index.html.md
  content/source/docs/plugin/framework/providers.html.md
  content/source/docs/plugin/framework/publishing.html.md
  content/source/docs/plugin/framework/resources.html.md
  content/source/docs/plugin/framework/schemas.html.md
  content/source/docs/plugin/framework/types.html.md
  content/source/docs/plugin/framework/writing-state.html.md
  content/source/docs/plugin/which-sdk.html.md
  content/source/layouts/extend.erb
Labels: extending, new docs, tw-reviewed

#1780 Add link to learn guide to framework sidebar.
  content/source/layouts/extend.erb
Labels: extending, learn

#1781 Remove anchors that no longer exist
  content/source/docs/plugin/framework/providers.html.md
Labels: cosmetic bug

#1763 Adding Terraform Enterprise security model
  content/source/docs/enterprise/before-installing/index.html.md
  content/source/docs/enterprise/system-overview/security-model.html.md
  content/source/layouts/_enterprise_content.erb
Labels: new docs, tw-reviewed

#1776 RFC TF-388
  content/source/docs/extend/best-practices/versioning.html.md
Labels: clarification, tw-reviewed

#1786 Scope broken link checker to just docs page
  .circleci/config.yml
Labels: CircleCI, tw-reviewed

#1788 Fixing issue with bulleted list not being formatted properly
  content/source/docs/enterprise/system-overview/security-model.html.md
Labels: cosmetic bug

#1773 Providing additional details of the parameters of the module creation API
  content/source/docs/cloud/api/modules.html.md
Labels: clarification, tfc, tw-reviewed

#1784 Add note for s3 bucket
  content/source/docs/enterprise/before-installing/reference-architecture/aws.md
Labels: clarification, tw-reviewed

#1794 content/source/docs/extend: Fix additional redirects
  content/source/docs/extend/best-practices/deprecations.md
  content/source/docs/extend/best-practices/sensitive-state.html.md
  content/source/docs/extend/best-practices/testing.html.md
  content/source/docs/extend/guides/v1-upgrade-guide.html.md
  content/source/docs/extend/resources/customizing-differences.html.md
  content/source/docs/extend/schemas/index.html.md
  content/source/docs/extend/schemas/schema-behaviors.html.md
  content/source/docs/extend/schemas/schema-methods.html.md
  content/source/docs/extend/schemas/schema-types.html.md
  content/source/docs/extend/terraform-0.12-compatibility.html.md
  content/source/docs/extend/testing/acceptance-tests/testcase.html.md
  content/source/docs/extend/testing/acceptance-tests/teststep.html.md
Labels: extending

#1747 update Read state outputs permission description
  content/source/docs/cloud/users-teams-organizations/permissions.html.md
Labels: clarification, tfc, tw-reviewed

#1791 Add subtitles to increase readability
  content/source/docs/enterprise/before-installing/network-requirements.html.md
Labels: clarification

#1785 Update azure-ad.html.md
  content/source/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html.md
Labels: cosmetic bug, tw-reviewed

#1797 content/source/docs/extend: Add Debugging Providers link to SDKv2 Upgrade Guide
  content/source/docs/extend/guides/v2-upgrade-guide.html.md
Labels: clarification, extending

#1795 content/source/docs/extend: Adjust links on acceptance testing index page
  content/source/docs/extend/testing/acceptance-tests/index.html.md
Labels: extending, inaccuracy

#1796 content/source/docs/extend: Revamp TestStep built in function section
  content/source/docs/extend/testing/acceptance-tests/teststep.html.md
Labels: clarification, extending
