Repository hashicorp/terraform-website, pull requests merged in 2021-12, with the labels that each got.

#1975 Update audit-trails.html.md
  content/source/docs/cloud/api/audit-trails.html.md
Labels: tfc, tw-reviewed, enterprise

#1985 docs/plugin/framework: Update publishing page flow and add goreleaser configuration
  content/source/docs/plugin/framework/publishing.html.md
Labels: clarification, extending, tw-reviewed

#1944 Various improvements to Enforce and Override page
  content/source/docs/cloud/sentinel/enforce.html.md
Labels: inaccuracy, clarification, tfc, tw-reviewed

#1953 Tf api/pagination 2
  content/source/docs/cloud/api/workspace-resources.html.md
  content/source/layouts/_cloud_content.erb
Labels: enhancement, new docs, tfc, tw-reviewed, api

#1990 docs/extend/resources/retries-and-customizable-timeouts: Clarify CRUD function defaults and recommendations
  content/source/docs/extend/resources/retries-and-customizable-timeouts.html.md
Labels: clarification, extending

#1993 OAuth API: Update Docs to explain key, secret, and rsa_public_key
  content/source/docs/cloud/api/changelog.html.md
  content/source/docs/cloud/api/oauth-clients.html.md
Labels: tw-reviewed

#1989 Redirect docs/plugin/framework/publishing.html to docs/registry/providers/publishing.html
  content/redirects.txt
  content/source/docs/extend/index.html.md
  content/source/docs/plugin/framework/index.html.md
  content/source/docs/plugin/framework/publishing.html.md
  content/source/docs/registry/providers/publishing.html.md
  content/source/layouts/extend.erb
Labels: clarification, extending, tw-reviewed

#1992 Update Docker Engine requirements
  content/source/docs/enterprise/before-installing/centos-requirements.html.md
  content/source/docs/enterprise/before-installing/index.html.md
  content/source/docs/enterprise/before-installing/rhel-requirements.html.md
Labels: clarification, tw-reviewed

#1998 Remove unnecessary requirements
  content/source/docs/enterprise/before-installing/rhel-requirements.html.md
Labels: inaccuracy

#1984 VMware documentation changes
  content/source/docs/enterprise/before-installing/reference-architecture/index.html.md
  content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
  content/source/docs/enterprise/install/active-active.html.md
  content/source/docs/enterprise/install/uninstall.html.md
Labels: tw-reviewed

#1777 Adding 'Updating Terraform Enterprise License' section to Application Administration section
  content/source/docs/cloud/run/api.html.md
  content/source/docs/enterprise/admin/images/airgap-checksum.png
  content/source/docs/enterprise/admin/images/console-settings.png
  content/source/docs/enterprise/admin/images/license-expiration.png
  content/source/docs/enterprise/admin/images/license-sync.png
  content/source/docs/enterprise/admin/images/sync-license.png
  content/source/docs/enterprise/admin/images/upload-license.png
  content/source/docs/enterprise/admin/images/view-license.png
  content/source/docs/enterprise/admin/update-tfe-license.html.md
  content/source/layouts/_enterprise_content.erb
Labels: new docs, tw-reviewed, enterprise

#1967 docs/plugin/framework: Initial validation page
  content/source/docs/plugin/framework/data-sources.html.md
  content/source/docs/plugin/framework/providers.html.md
  content/source/docs/plugin/framework/resources.html.md
  content/source/docs/plugin/framework/validation.html.md
  content/source/layouts/extend.erb
Labels: new docs, extending, tw-reviewed

#1977 docs/plugin/framework: Initial plan modification page
  content/source/docs/plugin/framework/plan-modification.html.md
  content/source/docs/plugin/framework/resources.html.md
  content/source/layouts/extend.erb
Labels: new docs, extending, tw-reviewed

#1991 [DO NOT MERGE] Update TFC Documentation for Cloud Blocks
  content/source/docs/cloud/api/index.html.md
  content/source/docs/cloud/api/workspaces.html.md
  content/source/docs/cloud/migrate/index.html.md
  content/source/docs/cloud/migrate/workspaces.html.md
  content/source/docs/cloud/overview.html.md
  content/source/docs/cloud/run/cli.html.md
  content/source/docs/cloud/run/index.html.md
  content/source/docs/cloud/run/run-environment.html.md
  content/source/docs/cloud/run/ui.html.md
  content/source/docs/cloud/workspaces/configurations.html.md
  content/source/docs/cloud/workspaces/index.html.md
  content/source/docs/cloud/workspaces/settings.html.md
  content/source/docs/cloud/workspaces/state.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs, tfc

#1978 Terraform Cloud per-run variables
  content/source/docs/cloud/workspaces/images/variable-precedence-example.png
  content/source/docs/cloud/workspaces/managing-variables.html.md
  content/source/docs/cloud/workspaces/variables.html.md
Labels: tw-reviewed

#1999 Document 'Require Site Admins to Enable Two-factor Authentication'
  content/source/docs/enterprise/admin/general.html.md
Labels: new docs, tw-reviewed, enterprise

#2008 remove outdated note
  content/source/docs/enterprise/admin/agents-on-tfe.html.md
Labels: clarification

#2015 Create TFE v202112-2 Release Notes
  content/enterprise/release/v202112-2.mdx
  data/enterprise-nav-data.json
Labels: tw-reviewed

#2033 plugin: Recommend Terraform v1.0 for framework instead of v1.0.3
  content/plugin/framework/index.mdx
  content/plugin/which-sdk.mdx
Labels: clarification, extending

#2042 Fix note format
  content/plugin/framework/validation.mdx
Labels: clarification, extending

#2032 plugin/framework: Add Resource Import page
  content/plugin/framework/resources/import.mdx
  content/plugin/framework/resources/index.mdx
  data/plugin-nav-data.json
Labels: new docs, extending

#2035 plugin: Add terraform-provider-scaffolding and terraform-provider-scaffolding-framework CTAs
  content/plugin/framework/index.mdx
  content/plugin/index.mdx
  content/plugin/sdkv2/sdkv2-intro.mdx
Labels: extending
