Repository hashicorp/terraform-website, pull requests merged in 2021-09, with the labels that each got.

#1814 Update Using Private Modules page
  content/source/docs/cloud/registry/using.html.md
Labels: clarification, tfc

#1847 Add vcs webhook note
  content/source/docs/cloud/vcs/troubleshooting.html.md
  content/source/docs/cloud/workspaces/creating.html.md
Labels: clarification, tfc

#1846 Update create app instructions on DevOps website
  content/source/docs/cloud/vcs/azure-devops-services.html.md
  content/source/docs/cloud/vcs/images/azure-devops-services-user-settings.png
Labels: inaccuracy, tfc

#1849 document capacity_cpus TFE option
  content/source/docs/enterprise/install/automating-the-installer.html.md
  content/source/docs/enterprise/system-overview/capacity.html.md
Labels: new docs, tw-reviewed

#1852 Fix broken links
  content/source/docs/enterprise/before-installing/reference-architecture/aws.md
  content/source/docs/enterprise/before-installing/reference-architecture/azure.md
  content/source/docs/enterprise/before-installing/reference-architecture/gcp.md
Labels: inaccuracy

#1839 Update planned state description
  content/source/docs/cloud/run/states.html.md
Labels: inaccuracy, tw-reviewed

#1854 Run checks
  content/source/docs/cloud/api/run-tasks.html.md
  content/source/docs/cloud/integrations/run-tasks/images/terraform-cloud-run-tasks-diagram.png
  content/source/docs/cloud/integrations/run-tasks/index.html.md
  content/source/docs/cloud/overview.html.md
  content/source/docs/cloud/run/states.html.md
  content/source/docs/cloud/users-teams-organizations/organizations.html.md
  content/source/docs/cloud/workspaces/images/run-tasks-add-to-workspace.png
  content/source/docs/cloud/workspaces/images/run-tasks-blank-event-hooks.png
  content/source/docs/cloud/workspaces/images/run-tasks-delete-hook-warning.png
  content/source/docs/cloud/workspaces/images/run-tasks-event-hooks-populated.png
  content/source/docs/cloud/workspaces/images/run-tasks-final-workspace-configuration.png
  content/source/docs/cloud/workspaces/images/run-tasks-run-failed.png
  content/source/docs/cloud/workspaces/images/run-tasks-run-success.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-settings.png
  content/source/docs/cloud/workspaces/images/run-tasks-workspace-tasks-populated.png
  content/source/docs/cloud/workspaces/run-tasks.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs

#1845 Update example responses for organizations API
  content/source/docs/cloud/api/organizations.html.md
Labels: inaccuracy, tfc

#1862 docs/plugin/framework: Update code examples for v0.3.0 breaking changes
  content/source/docs/plugin/framework/accessing-values.html.md
  content/source/docs/plugin/framework/data-sources.html.md
  content/source/docs/plugin/framework/resources.html.md
  content/source/docs/plugin/framework/schemas.html.md
  content/source/docs/plugin/framework/types.html.md
  content/source/docs/plugin/framework/writing-state.html.md
Labels: inaccuracy, extending

#1864 docs/plugin/framework: Update diagnostics for v0.3.0 diag package
  content/source/docs/plugin/framework/diagnostics.html.md
Labels: new docs, extending

#1851 Add documentation for log forwarding
  content/source/docs/enterprise/admin/logging.html.md
  content/source/docs/enterprise/before-installing/reference-architecture/aws.md
  content/source/docs/enterprise/before-installing/reference-architecture/azure.md
  content/source/docs/enterprise/before-installing/reference-architecture/gcp.md
  content/source/docs/enterprise/install/automating-the-installer.html.md
  content/source/layouts/_enterprise_content.erb
Labels: new docs, tw-reviewed

#1858 add documentation for terraform cloud agents on tfe
  content/source/docs/cloud/agents/index.html.md
  content/source/docs/enterprise/admin/agents-on-tfe.html.md
  content/source/layouts/_enterprise_content.erb
Labels: new docs, tw-reviewed, enterprise

#1860 Added proposed changes
  content/source/docs/cloud/users-teams-organizations/permissions.html.md
Labels: clarification, tfc, tw-reviewed

#1863 docs/plugin/framework: Clarify new capabilities provided by v0.3.0
  content/source/docs/plugin/framework/schemas.html.md
  content/source/docs/plugin/framework/types.html.md
  content/source/docs/plugin/which-sdk.html.md
Labels: clarification, extending

#1873 Update modules.html.md
  content/source/docs/cloud/api/modules.html.md
Labels: inaccuracy, tfc, tw-reviewed

#1875 Tf api/fixes and cleanup
  content/source/docs/cloud/api/agent-tokens.md
  content/source/docs/cloud/api/agents.md
  content/source/docs/cloud/api/invoices.html.md
  content/source/docs/cloud/api/organization-memberships.html.md
  content/source/docs/cloud/api/run-triggers.html.md
Labels: clarification, tfc, api

#1876 Update TFC variables page
  content/source/docs/cloud/workspaces/variables.html.md
Labels: clarification, tfc

#1881 document support for rhel7-based tfe custom worker images
  content/source/docs/enterprise/install/installer.html.md
Labels: ptfe, clarification

#1872 docs/plugin/framework: Updates for v0.4.0 import, Set, Int64, and Float64 support
  content/source/docs/plugin/framework/resources.html.md
  content/source/docs/plugin/framework/types.html.md
  content/source/docs/plugin/which-sdk.html.md
Labels: new docs, extending

#1882 document publicly curated modules
  content/source/docs/cloud/registry/add.html.md
  content/source/docs/cloud/registry/images/add-add-button.png
  content/source/docs/cloud/registry/images/add-add-to-terraform-cloud-button.png
  content/source/docs/cloud/registry/images/add-delete-module-button.png
  content/source/docs/cloud/registry/images/add-delete-module-dialog.png
  content/source/docs/cloud/registry/images/add-find-button.png
  content/source/docs/cloud/registry/images/add-search-public-modules.png
  content/source/docs/cloud/registry/images/publish-add-button.png
  content/source/docs/cloud/registry/images/using-modules-button.png
  content/source/docs/cloud/registry/images/using-modules-list.png
  content/source/docs/cloud/registry/index.html.md
  content/source/docs/cloud/registry/publish.html.md
  content/source/docs/cloud/registry/using.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs, cosmetic bug, clarification, tfc

#1885 Fix Private Registry broken link and images
  content/source/docs/cloud/registry/design.html.md
  content/source/docs/cloud/registry/images/design-add-module.png
  content/source/docs/cloud/registry/images/design-select-modules.png
  content/source/docs/cloud/registry/images/design-set-version.png
  content/source/docs/cloud/registry/images/design-start.png
  content/source/docs/cloud/registry/images/design-variables-finished.png
  content/source/docs/cloud/registry/images/design-variables-help.png
  content/source/docs/cloud/registry/images/design-verify.png
  content/source/docs/cloud/registry/images/publish-add-button.png
  content/source/docs/cloud/registry/images/publish-add-module.png
  content/source/docs/cloud/registry/images/publish-module-details.png
  content/source/docs/cloud/registry/images/using-modules-list-shared.png
  content/source/docs/cloud/registry/images/using-modules-list-sharing.png
  content/source/docs/cloud/registry/images/using-submodules-dropdown.png
  content/source/docs/cloud/registry/publish.html.md
  content/source/docs/cloud/registry/using.html.md
  content/source/docs/extend/testing/testing-patterns.html.md
Labels: tfc
