Repository hashicorp/terraform-website, pull requests merged in 2021-01, with the labels that each got.

#1578 Update provider locations documentation.
  content/source/docs/extend/how-terraform-works.html.md
Labels: clarification, extending, inaccuracy

#1579 Update index.html.md
  content/source/docs/cloud/agents/index.html.md
Labels: clarification

#1585 Policy checks API: add show endpoint, include run relationship
  content/source/docs/cloud/api/policy-checks.html.md
Labels: inaccuracy

#1574 Improved PR link checking, finally
  .circleci/config.yml
  content/scripts/check-pr-links.rb
Labels: enhancement

#1583 TF-288 Required Encryption Password
  content/source/docs/enterprise/install/assets/enc-password-manual-install.png
  content/source/docs/enterprise/install/automating-the-installer.html.md
  content/source/docs/enterprise/install/encryption-password.html.md
Labels: new docs

#1591 Ea/aa ra
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-AA-AWS-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-AA-Azure-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-AA-GCP-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-SA-AWS-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-SA-Azure-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-SA-GCP-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/aws.md
  content/source/docs/enterprise/before-installing/reference-architecture/azure.md
  content/source/docs/enterprise/before-installing/reference-architecture/gcp.md
Labels: clarification, ptfe

#1595 Added Active/Active scaling guide
  content/source/docs/enterprise/install/active-active.html.md
  content/source/layouts/_enterprise_content.erb
Labels: ptfe

#1596 ea/aa-fix
  content/source/docs/enterprise/before-installing/reference-architecture/assets/RA-TFE-AA-Azure-SingleRegion.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/aws-infrastructure-diagram.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/azure-infrastructure-diagram.png
  content/source/docs/enterprise/before-installing/reference-architecture/assets/gcp-infrastructure-diagram.png
  content/source/docs/enterprise/before-installing/reference-architecture/aws.md
  content/source/docs/enterprise/before-installing/reference-architecture/azure.md
  content/source/docs/enterprise/before-installing/reference-architecture/gcp.md
Labels: clarification, inaccuracy

#1598 Updating Ubuntu supported version adding 20.04
  content/source/docs/enterprise/before-installing/index.html.md
Labels: inaccuracy

#1594 Revamp the README for the current state of the world
  README.md
Labels: inaccuracy

#1593 PR link check: add special casing for Vercel routes
  content/scripts/check-pr-links.rb
Labels: enhancement

#1605 Add supplementary redirects for implied index URLs
  content/redirects.txt
Labels: cosmetic bug
