Repository hashicorp/terraform-website, pull requests merged in 2021-05, with the labels that each got.

#1709 Updating the referencd to install Docker EE in RHEL
  content/source/docs/enterprise/before-installing/rhel-requirements.html.md
Labels: inaccuracy

#1713 Adding the Terraform Cloud security model
  content/source/assets/images/docs/terraform-cloud-authorization.png
  content/source/docs/cloud/architectural-details/security-model.html.md
  content/source/layouts/_cloud_content.erb
Labels: new docs

#1714 Fixing broken link
  content/source/docs/cloud/architectural-details/security-model.html.md
Labels: cosmetic bug

#1711 Update RHEL/CentOS Docker documentation
  content/source/docs/enterprise/before-installing/centos-requirements.html.md
  content/source/docs/enterprise/before-installing/rhel-requirements.html.md
Labels: clarification

#1721 add agents to how TFC can run TF
  content/source/docs/cloud/overview.html.md
Labels: clarification

#1722 Add link to Learn tutorial
  content/source/docs/cloud/api/state-versions.html.md
Labels: clarification

#1727 Add delete endpoint to agent API docs
  content/source/docs/cloud/api/agents.md
Labels: new docs, tfc
