Repository hashicorp/terraform-website, pull requests merged in 2022-09, with the labels that each got.

#2413 [Partner Badge] Update image to use handshake asset.
  components/provider-table/index.jsx
  public/img/docs/partner-tier-new.png
Labels: terraform registry

#2407 Redirect drift docs to health assessments
  redirects.next.js
Labels: tfc

#2342 [DO NOT MERGE UNTIL v1.3] Add redirect for optional types attributes page
  redirects.next.js
Labels: terraform core
