Repository hashicorp/terraform-website, pull requests merged in 2022-02, with the labels that each got.

#2110 Remove Clustered documentation and add redirects
  content/enterprise/admin/infrastructure/active-active.mdx
  content/enterprise/before-installing/cluster-architecture.mdx
  content/enterprise/before-installing/reference-architecture/index.mdx
  content/enterprise/install/cluster-aws.mdx
  content/enterprise/install/cluster-azure.mdx
  content/enterprise/install/cluster-custom.mdx
  content/enterprise/install/cluster-gcp.mdx
  data/enterprise-nav-data.json
  redirects.next.js
Labels: inaccuracy, enterprise

#2121 Add log rotation information
  content/enterprise/admin/infrastructure/logging.mdx
  content/enterprise/before-installing/index.mdx
  content/enterprise/release/v202109-1.mdx
  content/enterprise/release/v202109-2.mdx
Labels: tw-reviewed

#2105 fix: you can't actually update the key text for an existing SSH key
  content/cloud-docs/api-docs/ssh-keys.mdx
Labels: tw-reviewed

#2124 Update installer.mdx
  content/enterprise/install/interactive/installer.mdx
Labels: tw-reviewed

#2119 Remove pre apply stage
  content/cloud-docs/api-docs/run-tasks.mdx
  content/cloud-docs/integrations/run-tasks/index.mdx
  content/cloud-docs/run/states.mdx
Labels: tfc, tw-reviewed

#2134 Change wording for better understanding
  content/plugin/sdkv2/schemas/schema-behaviors.mdx
Labels: clarification, extending, tw-reviewed

#2150 [TF-451] Update API documentation for Run Task endpoints
  content/cloud-docs/api-docs/run-tasks.mdx
  content/cloud-docs/users-teams-organizations/organizations.mdx
  content/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: tw-reviewed

#2137 Madaleines/private providers docs
  .gitignore
  content/cloud-docs/agents/changelog.mdx
  content/cloud-docs/agents/hooks.mdx
  content/cloud-docs/api-docs/changelog.mdx
  content/cloud-docs/api-docs/modules.mdx
  content/cloud-docs/api-docs/providers.mdx
  content/cloud-docs/api-docs/run-tasks.mdx
  content/cloud-docs/users-teams-organizations/organizations.mdx
  content/cloud-docs/vcs/github.mdx
  content/cloud-docs/workspaces/settings/run-tasks.mdx
  content/enterprise/releases/2022/index.mdx
  content/enterprise/releases/2022/v202202-1.mdx
  content/enterprise/releases/index.mdx
  data/cloud-docs-nav-data.json
  data/enterprise-nav-data.json
Labels: in progress, new docs, providers, api
