Repository hashicorp/terraform-website, pull requests merged in 2022-04, with the labels that each got.

#2241 Update variable-sets.mdx
  content/cloud-docs/api-docs/variable-sets.mdx
Labels: clarification, tw-reviewed

#2250 Add default log rotation settings to the `04-2` patch release
  content/enterprise/releases/2022/v202204-2.mdx
Labels: new docs

#2251 Update tfc-agent changelog
  content/cloud-docs/agents/changelog.mdx
Labels: new docs

#2256 plugin: Update tfsdk.NewProtocol6Server usage with new functions
  content/plugin/framework/acctests.mdx
  content/plugin/mux/combining-protocol-version-6-providers.mdx
  content/plugin/mux/translating-protocol-version-5-to-6.mdx
  content/plugin/mux/translating-protocol-version-6-to-5.mdx
Labels: clarification, extending

#2255 plugin/framework: Initial State Upgrade information
  content/plugin/framework/resources/index.mdx
  content/plugin/framework/resources/state-upgrade.mdx
  content/plugin/which-sdk.mdx
  data/plugin-nav-data.json
Labels: new docs, extending

#2261 Update "queue plan" button text
  content/cloud-docs/run/index.mdx
Labels: inaccuracy, tw-address

#2271 Update callback status docs to outline allowed statuses
  content/cloud-docs/api-docs/run-tasks-integration.mdx
Labels: tfc, api

#2274 Fix Broken Markdown on Sentinel Docs Page
  content/cloud-docs/sentinel/import/tfconfig-v2.mdx
Labels: cosmetic bug, tfc
