Repository hashicorp/terraform-website, pull requests merged in 2022-05, with the labels that each got.

#2275 Fix copy with updates from review
  content/cloud-docs/api-docs/run-tasks-integration.mdx
Labels: tfc

#2268 plugin/framework: Ensure rest of v0.7.0 updates are captured
  content/plugin/framework/debugging.mdx
  content/plugin/framework/resources/import.mdx
  content/plugin/framework/resources/index.mdx
  content/plugin/framework/schemas.mdx
Labels: clarification, extending

#2269 plugin+registry: Capture pre-step with GitHub Actions usage to ensure its allowed
  content/plugin/sdkv2/testing/acceptance-tests/index.mdx
  content/registry/providers/publishing.mdx
Labels: clarification, extending

#2276 plugin/sdkv2: Fix sdkv2-intro page to be index page
  content/docs/terraform-tools.mdx
  content/plugin/framework/index.mdx
  content/plugin/mux/combining-protocol-version-5-providers.mdx
  content/plugin/mux/combining-protocol-version-6-providers.mdx
  content/plugin/mux/index.mdx
  content/plugin/mux/translating-protocol-version-5-to-6.mdx
  content/plugin/mux/translating-protocol-version-6-to-5.mdx
  content/plugin/sdkv2/index.mdx
  content/plugin/sdkv2/sdkv2-intro.mdx
  content/registry/providers/publishing.mdx
  data/docs-redirects.js
  data/other-plugins-nav-data.json
  data/plugin-sdk-nav-data.json
  redirects.next.js
Labels: extending

#2277 data: Remove extend-nav-data
  data/extend-nav-data.json
Labels: extending

#2280 Update rate limit messaging
  content/cloud-docs/api-docs/index.mdx
  content/enterprise/admin/application/general.mdx
Labels: tfc, api

#2285 Update tfc-agent changelog
  content/cloud-docs/agents/changelog.mdx
Labels: new docs

#2290 very minor fixes
  content/cloud-docs/api-docs/run.mdx
Labels: cosmetic bug

#2270 Update creating workspaces and managing variables docs
  content/cloud-docs/workspaces/creating.mdx
  content/cloud-docs/workspaces/variables/managing-variables.mdx
Labels: enhancement, tfc, enterprise

#2286 Ready Run Task Docs for GA
  content/cloud-docs/api-docs/run-tasks-integration.mdx
  content/cloud-docs/api-docs/run-tasks.mdx
  content/cloud-docs/integrations/run-tasks/index.mdx
  content/cloud-docs/workspaces/settings/run-tasks.mdx
  public/img/docs/run-tasks-add-to-workspace.png
  public/img/docs/run-tasks-blank-event-hooks.png
  public/img/docs/run-tasks-delete-hook-warning.png
  public/img/docs/run-tasks-delete-run-task-warning.png
  public/img/docs/run-tasks-empty-run-tasks.png
  public/img/docs/run-tasks-event-hooks-populated.png
  public/img/docs/run-tasks-final-workspace-configuration.png
  public/img/docs/run-tasks-run-failed.png
  public/img/docs/run-tasks-run-success.png
  public/img/docs/run-tasks-run-tasks-populated.png
  public/img/docs/run-tasks-workspace-remove.png
  public/img/docs/run-tasks-workspace-run-tasks-populated.png
  public/img/docs/run-tasks-workspace-settings.png
  public/img/docs/run-tasks-workspace-tasks-populated.png
Labels: new docs

#2263 Add Run Tasks Entitlement to API Docs
  content/cloud-docs/api-docs/feature-sets.mdx
  content/cloud-docs/api-docs/index.mdx
  content/cloud-docs/api-docs/organizations.mdx
  content/cloud-docs/api-docs/subscriptions.mdx
Labels: tfc, tw-reviewed

#2291 Add notes on run tasks token permissions
  content/cloud-docs/users-teams-organizations/permissions.mdx
Labels: tfc

#2294 Add messaging around the post-plan stage
  content/cloud-docs/run/states.mdx
Labels: tfc

#2297 Add a note about GCP Redis in-transit encryption
  content/enterprise/install/automated/active-active.mdx
Labels: clarification, tw-reviewed

#2300 Replace images from API changelog
  content/cloud-docs/api-docs/changelog.mdx
Labels: cosmetic bug

#2068 Update index.mdx
  content/enterprise/before-installing/index.mdx
Labels: tw-reviewed

#2304 Remove sneaky final beta tag for run tasks
  content/cloud-docs/users-teams-organizations/organizations.mdx
  content/cloud-docs/workspaces/settings/run-tasks.mdx
Labels: inaccuracy

#2295 Add missing run tasks examples
  content/cloud-docs/api-docs/organizations.mdx
  content/cloud-docs/api-docs/team-access.mdx
  content/cloud-docs/api-docs/teams.mdx
Labels: tfc

#2308 Add clarification on managing team membership through SSO, and the SSO Team ID
  content/cloud-docs/users-teams-organizations/single-sign-on/azure-ad.mdx
  content/cloud-docs/users-teams-organizations/single-sign-on/index.mdx
  content/cloud-docs/users-teams-organizations/teams.mdx
Labels: clarification

#2305 Retrospectively update changelog for Run Tasks
  content/cloud-docs/api-docs/changelog.mdx
Labels: clarification, api

#2306 Update active/active documentation.
  content/enterprise/install/automated/active-active.mdx
Labels: clarification, enterprise

#2316 Update tfc-agent changelog
  content/cloud-docs/agents/changelog.mdx
Labels: new docs

#2310 Non-Interactive Workflows
  content/cloud-docs/run/cli.mdx
Labels: clarification, tfc

#2320 Clarify that workspace admins cannot manage secret teams
  content/cloud-docs/users-teams-organizations/permissions.mdx
Labels: clarification, content:cloud-docs

#2314 Reorganize Terraform Cloud Sidebar
  content/cloud-docs/index.mdx
  content/cloud-docs/overview.mdx
  content/cloud-docs/paid.mdx
  content/cloud-docs/recommended-practices/index.mdx
  content/cloud-docs/recommended-practices/part1.mdx
  content/cloud-docs/recommended-practices/part2.mdx
  content/cloud-docs/recommended-practices/part3.1.mdx
  content/cloud-docs/recommended-practices/part3.2.mdx
  content/cloud-docs/recommended-practices/part3.3.mdx
  content/cloud-docs/recommended-practices/part3.4.mdx
  content/cloud-docs/recommended-practices/part3.mdx
  content/cloud-docs/run/remote-operations.mdx
  data/cloud-docs-nav-data.json
  data/enterprise-nav-data.json
  redirects.next.js
Labels: clarification, tfc, improvement, content:enterprise, content:cloud-docs

#2313 Upgrading terraform cloud in the UI using plan-only and allow-empty-apply runs
  content/cloud-docs/api-docs/run.mdx
  content/cloud-docs/run/modes-and-options.mdx
  content/cloud-docs/run/ui.mdx
  content/cloud-docs/workspaces/state.mdx
Labels: new docs, tfc, api, content:cloud-docs
