Repository hashicorp/terraform-website, pull requests merged in 2022-01, with the labels that each got.

#2055 Refer to non-deprecated helper
  content/plugin/sdkv2/schemas/schema-types.mdx
Labels: inaccuracy, extending

#2052 plugin/sdkv2: Fix various formatting issues
  content/plugin/sdkv2/schemas/schema-behaviors.mdx
  content/plugin/sdkv2/schemas/schema-types.mdx
  content/plugin/sdkv2/testing/acceptance-tests/testcase.mdx
Labels: cosmetic bug, extending, tw-reviewed

#2057 data: Add missing redirect for Learn collection on Terraform Providers
  data/docs-redirects.js
Labels: inaccuracy, extending

#2071 Fix Attribute Validator example
  content/plugin/framework/validation.mdx
Labels: inaccuracy, extending

#2076 Making run-specific variables JSON friendly for the payload
  content/cloud-docs/api-docs/run.mdx
Labels: tfc, tw-reviewed

#2084 Update private registry permissions
  content/cloud-docs/registry/add.mdx
  content/cloud-docs/registry/index.mdx
  content/cloud-docs/registry/publish.mdx
  content/cloud-docs/users-teams-organizations/permissions.mdx
  content/cloud-docs/users-teams-organizations/teams.mdx
  public/img/docs/teams-team-settings.png
Labels: new docs, tfc

#2085 Add a note to explicitly call out that TFE VCS Integration with a SaaS VCS provider requires inbound connectivity
  content/cloud-docs/vcs/index.mdx
  content/enterprise/before-installing/network-requirements.mdx
Labels: tw-reviewed

#2063 Update api docs for updated global variable sets
  content/cloud-docs/api-docs/variable-sets.mdx
Labels: tw-reviewed

#2051 Update docs for State Versions API fix
  content/cloud-docs/api-docs/state-versions.mdx
Labels: tfc, api

#2092 docs: add schemaValidateDiagFunc
  content/plugin/sdkv2/schemas/schema-behaviors.mdx
Labels: clarification, extending

#2080 Update ServiceNow versions
  content/cloud-docs/integrations/service-now/index.mdx
Labels: tw-reviewed

#2054 Add documentation for logging.
  content/plugin/log/managing.mdx
  content/plugin/log/writing.mdx
  content/plugin/sdkv2/debugging.mdx
  content/plugin/sdkv2/testing/acceptance-tests/index.mdx
  data/plugin-nav-data.json
Labels: new docs, extending

#2097 document newly-minted TFE metrics
  content/enterprise/admin/infrastructure/monitoring.mdx
  content/enterprise/install/automated/automating-the-installer.mdx
Labels: enhancement, enterprise

#2091 Update index.mdx
  content/enterprise/before-installing/index.mdx
Labels: ptfe, clarification, tw-reviewed

#2100 plugin/sdkv2/debugging: Add VS Code and clarify Delve CLI usage
  content/plugin/sdkv2/debugging.mdx
Labels: clarification, extending, tw-reviewed

#2098 plugin/framework/acctests: Add root id attribute requirement information
  content/plugin/framework/acctests.mdx
Labels: clarification, extending, tw-reviewed

#2102 add grafana dasboard link
  content/enterprise/admin/infrastructure/monitoring.mdx
Labels: clarification, tw-reviewed, enterprise
