Repository hashicorp/terraform-website, pull requests merged in 2023-01, with the labels that each got.

#2457 Update redirects.js
  redirects.js
Labels: tfc

#2458 docs: updates generated docs
  README.md
  package-lock.json
  package.json
Labels: dependencies, web platform

#2464 Add redirect from module-sharing to registry-sharing
  redirects.next.js
Labels: ptfe, inaccuracy
